-- Cart table for persistent storage
create table if not exists cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references items(id) on delete cascade,
  quantity int not null default 1,
  created_at timestamp with time zone default now(),
  unique(user_id, item_id)
);

-- Enable RLS
alter table cart_items enable row level security;

-- Policies
create policy "Users can view their own cart items"
  on cart_items for select
  using (auth.uid() = user_id);

create policy "Users can insert into their own cart"
  on cart_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own cart items"
  on cart_items for update
  using (auth.uid() = user_id);

create policy "Users can delete their own cart items"
  on cart_items for delete
  using (auth.uid() = user_id);